// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { GameRounds, GameRoundsTableId } from "./tables/GameRounds.sol";
import { Player, PlayerData, PlayerTableId } from "./tables/Player.sol";
import { GameStatus, GameStatusTableId } from "./tables/GameStatus.sol";
import { Victim, VictimTableId } from "./tables/Victim.sol";
import { GroupChatID, GroupChatIDTableId } from "./tables/GroupChatID.sol";
import { PlayersIDList, PlayersIDListTableId } from "./tables/PlayersIDList.sol";
