// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { GameRounds, GameRoundsTableId } from "./tables/GameRounds.sol";
import { Players, PlayersData, PlayersTableId } from "./tables/Players.sol";
import { PlayersIDList, PlayersIDListTableId } from "./tables/PlayersIDList.sol";
import { GameStatus, GameStatusTableId } from "./tables/GameStatus.sol";
import { DayStatus, DayStatusTableId } from "./tables/DayStatus.sol";
import { Victim, VictimTableId } from "./tables/Victim.sol";
import { GroupChatID, GroupChatIDTableId } from "./tables/GroupChatID.sol";
import { Creator, CreatorTableId } from "./tables/Creator.sol";
import { FarmerCount, FarmerCountTableId } from "./tables/FarmerCount.sol";
import { WolfmanCount, WolfmanCountTableId } from "./tables/WolfmanCount.sol";
import { SYSTEM_MSG, SYSTEM_MSGTableId } from "./tables/SYSTEM_MSG.sol";
import { NickName, NickNameTableId } from "./tables/NickName.sol";
