// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum Actor {
  Farmer,
  Wolfman
}

enum Camp {
  Good,
  Bad
}

enum GameStatusEnum {
  UNSTART,
  STARTED,
  GAMEOVER
}

enum DayStatusEnum {
  DAY,
  NIGHT
}
