// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IIncrementSystem {
  function joinGame() external returns (bool);

  function increment() external returns (uint32);

  function randMod(uint _modulus) external returns (uint);

  function whispering(address target_user, string memory message) external returns (bool);

  function kill(address target_user) external returns (bool);

  function chooseVictim(address victim) external returns (bool);
}
